# Site settings
title: Onyx
email: onyx@spl.snu.ac.kr
description: >
  A Data Processing System for Flexible Employment With Different Deployment Characteristics.

baseurl: "/onyx" # the subpath of your site, e.g. /blog/
url: https://snuspl.github.io/onyx/ # the base hostname & protocol for your site
git_address: https://github.com/snuspl/onyx
git_edit_address: https://github.com/snuspl/onyx

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: readable

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Asia/Seoul
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _pages
    type: pages
  values:
    layout: page
    sectionid: pages
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  pages:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
