/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.nemo.runtime.executor.data;
import io.opencensus.common.ServerStatsFieldEnums;
import org.apache.nemo.common.Pair;

import java.util.ArrayList;
import java.util.LinkedList;
//import java.util.List;

/**
 * A class to estimate the size of outputs generated by BlockOutputWriter.
 * needed for storing the elements while tracking their size, to acquireMemory form MemoryManager
 */
public class SizeTrackingVector {
  private ArrayList<Object> vector;
  // rate of sampling growth rate
  private double sampleGrowthRate;
  private LinkedList<Pair<Long, Long>> samples;
  // number of updates/insertions since last update
  private long numUpdates;
  // average number of bytes between last two updates
  private long bytesPerUpdate;
  // value at which we will take our next sample
  private long nextSampleNum;


  SizeTrackingVector() {

  }


  private void resetSamples() {
    numUpdates = 1;
    nextSampleNum = 1;
    samples.clear();
    takeSample();
  }

  private void afterUpdate() {
    numUpdates += 1;
    if (nextSampleNum == numUpdates) {
      takeSample();
    }
  }

  /**
   * Append new item to vector.
   * @param element element to add to vector.
   */
  public void append(final Object element) {
    this.vector.add(element);
  }

  private void takeSample() {
//    Pair pair = Pair< SizeEstimator.estimate(1), numUpdates >;
    samples.add(Pair.of(SizeEstimator.estimate(4), numUpdates));
//    long bytesDelta = samples.getFirst() - samples.getLast();

  }


  /**
   * Method to estimate the size of the vector by taking samples.
   * @return size in bytes
   */
  public long estimateSize() {
    long size = 0;

    return size;
  }






}
